// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('e:/QlSanPhamm/node_modules/react');
var { Component } = React;
var ReactNative = require('e:/QlSanPhamm/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('QlSanPhamm', appParameters);
});
require('e:/QlSanPhamm/index.android.js');